In [8]:
import tensorflow as tf
import tensorflow_hub as hub
import pandas as pd
import numpy as np
import re
from matplotlib import pyplot as plt

In [15]:
dataset = pd.read_csv('news_summary.csv')#,encoding="ISO-8859-1")
dataset.head(4)

author                  date  \
0    Chhavi Tyagi  03 Aug 2017,Thursday   
1     Daisy Mowke  03 Aug 2017,Thursday   
2  Arshiya Chopra  03 Aug 2017,Thursday   
3   Sumedha Sehra  03 Aug 2017,Thursday   

                                           headlines  \
0  Daman & Diu revokes mandatory Rakshabandhan in...   
1  Malaika slams user who trolled her for 'divorc...   
2  Virgin' now corrected to 'Unmarried' in IGIMS'...   
3  Aaj aapne pakad liya: LeT man Dujana before be...   

                                           read_more  \
0  http://www.hindustantimes.com/india-news/raksh...   
1  http://www.hindustantimes.com/bollywood/malaik...   
2  http://www.hindustantimes.com/patna/bihar-igim...   
3  http://indiatoday.intoday.in/story/abu-dujana-...   

                                                text  \
0  The Administration of Union Territory Daman an...   
1  Malaika Arora slammed an Instagram user who tr...   
2  The Indira Gandhi Institute of Medical Science...   
3  Lashkar-e-Taiba's Kashmir commander Abu Dujana...   

                                               ctext  
0  The Daman and Diu administration on Wednesday ...  
1  From her special numbers to TV?appearances, Bo...  
2  The Indira Gandhi Institute of Medical Science...  
3  Lashkar-e-Taiba's Kashmir commander Abu Dujana...

In [71]:
dataset = dataset.dropna(how='any',axis=0) 
x = dataset['ctext']
y = dataset['text']
# x.datatype
# print(x[0])
t=[]
# print(len(x[0]))
# for i in range(len(x)):
#     for j in range(len(x[i])):
#         t.append(x[j].split("."))
# print(t)

t.append(x[0].split("."))
print(t[0][0])
print(len(t[0]))
for i in range(len(t[0])):
    t.append(t[0][i])
print(t)


# s= pd.Series([x[0],np.nan])
# print(s)
# li =[]
# s.str.split(pat=".")
# print(s[0])
# for i in x[0]:
#     c=0
#     if(i != '.'):
#         c+=1
#     else:
#         li.append()
        
headline = dataset['headlines']
print(headline)
# del dataset
# headline

The Daman and Diu administration on Wednesday withdrew a circular that asked women staff to tie rakhis on male colleagues after the order triggered a backlash from employees and was ripped apart on social media
18
[['The Daman and Diu administration on Wednesday withdrew a circular that asked women staff to tie rakhis on male colleagues after the order triggered a backlash from employees and was ripped apart on social media', 'The union territory?s administration was forced to retreat within 24 hours of issuing the circular that made it compulsory for its staff to celebrate Rakshabandhan at workplace', '?It has been decided to celebrate the festival of Rakshabandhan on August 7', ' In this connection, all offices/ departments shall remain open and celebrate the festival collectively at a suitable time wherein all the lady staff shall tie rakhis to their colleagues,? the order, issued on August 1 by Gurpreet Singh, deputy secretary (personnel), had said', 'To ensure that no one skipped 

In [32]:
# def preprocess_sentence(w,f):
#     w = w.lower().strip()

#     # creating a space between a word and the punctuation following it
#     # eg: "he is a boy." => "he is a boy ."
#     # Reference:- https://stackoverflow.com/questions/3645931/python-padding-punctuation-with-white-spaces-keeping-punctuation
#     w = re.sub(r"([?.!,¿])", r" \1 ", w)
#     w = re.sub(r'[" "]+', " ", w)

#     # replacing everything with space except (a-z, A-Z, ".", "?", "!", ",")
#     w = re.sub(r"[^a-zA-Z?.!,¿]+", " ", w)

#     w = w.rstrip().strip()

#     # adding a start and an end token to the sentence
#     # so that the model know when to start and stop predicting.
#     if(f==0):
#         w = '<start> '+ w + ' <end>'
#         f=1
#     return w

In [30]:
# def tokenize(lang):
#     lang_tokenizer = tf.keras.preprocessing.text.Tokenizer(filters='')
  
#     lang_tokenizer.fit_on_texts(lang)

#     tensor = lang_tokenizer.texts_to_sequences(lang)

#     tensor = tf.keras.preprocessing.sequence.pad_sequences(tensor, padding='post')

#     return tensor, lang_tokenizer

In [68]:
embed = hub.load("https://tfhub.dev/google/tf2-preview/nnlm-en-dim50/1")
embeddings = embed(t[0])
print(embeddings.shape)
embed()
# embeddings.shape([0])


(18, 50)


TypeError: 'TensorShape' object is not callable

In [60]:
# embeddings = embed(["cat is on the mat", "dog is in the fog"])
# print(embeddings[0].shape)

(50,)


In [58]:
# hub_layer = hub.KerasLayer("https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1",output_shape=[16],input_shape=[],dtype = tf.string)
# hub_layer(t[0][0])
print(embeddings.shape)

(18, 50)


In [33]:
# f=0
# x = [preprocess_sentence(w,f) for w in x]
# y = [preprocess_sentence(w,f) for w in y]
# headline = [preprocess_sentence(w,f) for w in headline]
# x_train, inp_lang = tokenize(x)
# y_train, targ_lang = tokenize(y)
# headline_train , headline_lang = tokenize(headline)
# print("Input Tensor Shape :" , x_train.shape , "Target Tensor Shape :" , y_train.shape)
# print("Preprocessed Text : \n" , x[0])
# # embeddings = embed(x[0])
# print("Tokenized Text INP : \n" , x_train[0])
# print("Tokenized Text OUT : \n" , y_train[0])

# print("Headline Text : \n" , headline[0])
# print("Headline Tokenized : \n" , headline_train[0])

Input Tensor Shape : (4395, 5801) Target Tensor Shape : (4395, 96)
Preprocessed Text : 
 <start> start start start start start the daman and diu administration on wednesday withdrew a circular that asked women staff to tie rakhis on male colleagues after the order triggered a backlash from employees and was ripped apart on social media . the union territory ? s administration was forced to retreat within hours of issuing the circular that made it compulsory for its staff to celebrate rakshabandhan at workplace . ? it has been decided to celebrate the festival of rakshabandhan on august . in this connection , all offices departments shall remain open and celebrate the festival collectively at a suitable time wherein all the lady staff shall tie rakhis to their colleagues , ? the order , issued on august by gurpreet singh , deputy secretary personnel , had said . to ensure that no one skipped office , an attendance report was to be sent to the government the next evening . the two notifi

In [43]:
class Encoder(tf.keras.Model):
    '''
    The code of encoder is used for text summarization. The model needs an initial_state which is the headline of the article.
    The input is supposed to be padded sequence for initial state as well as for the input. The model cuurently implements
    GRU for the encoder sequence as there is some bug with using lstm with bidirectional. Bidirectional was also tried with 
    GRU but same bug occured.
    
    The initialization is based on docuemnt context vector paper referenced from 
    https://arxiv.org/pdf/1807.08000.pdf paper named 
    Abstractive and Extractive Text Summarization using DocumentContext Vector and Recurrent Neural Networks.
    
    However the logic is modeified. The model takes the preprocessed tokenized padded sequence as input for initials state
    and the then it is passed through the embedded vector and the size of the output vector after embedding is (batch_size , time , embedding size)
    after this the model is averaged about the time axis and gives the output as (batch_size , embedding size).
    This tensor is then passed as input to dence vector and is used to give the output size of (batch_zie , lgur_hidden_units)
    '''
    def __init__(self,units = 16,activation='tanh',recurrent_activation='sigmoid',return_state=True,return_sequence=False , vocab_size=30000 , embedding_dim=30 , batch_size=2):
        super (Encoder , self).__init__()
        self.units = units
        self.activation = activation
        self.recurrent_activation = recurrent_activation
        self.return_state = return_state
        self.return_sequence = return_sequence
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.batch_size = batch_size
        self.embedding = tf.keras.layers.Embedding(vocab_size,embedding_dim)
#         self.lstm = tf.keras.layers.LSTM(units=self.units , activation=self.activation , recurrent_activation=self.activation, return_sequences=self.return_sequence , return_state=self.return_state)
        self.gru = tf.keras.layers.GRU(units=self.units , activation=self.activation , recurrent_activation=self.activation, return_sequences=self.return_sequence , return_state=self.return_state)
#         self.bidirectional = tf.keras.layers.Bidirectional(self.gru)
        self.dense = tf.keras.layers.Dense(units=self.units , input_shape = (self.embedding_dim,))
        print(self.gru)
        print(self.dense)
    
    def call(self,x,headline):
        x = self.embedding(x)
        headline = self.embedding(headline)
        headline = tf.reduce_mean(headline,axis=1)
        headline  = self.dense(headline)
        output , state = self.gru(x,initial_state=headline)
        print(headline)
        return output , state

In [44]:
encoder = Encoder()

In [45]:
# encoder(x_train[:2] , headline_train[:2])
output, state = encoder(x_train[:2] , headline_train[:2])
print(output)
print(state)

tf.Tensor(
[[-0.01274545  0.00377362  0.00176518  0.01666837  0.00011586 -0.00791561
  -0.00348736 -0.01001901 -0.02082361  0.00328003 -0.00442921 -0.00485594
   0.00675421 -0.01471758  0.00612056  0.00763087]
 [-0.01447946  0.00330228  0.00396879  0.0091158  -0.00728692 -0.00592501
  -0.000117   -0.0094883  -0.01375795  0.00186321 -0.00284222 -0.00010325
  -0.002235   -0.0089999   0.00074972  0.00753917]], shape=(2, 16), dtype=float32)
tf.Tensor(
[[ 0.01094229 -0.0115445   0.01160178 -0.03359373 -0.01112978  0.07763909
  -0.03779947  0.02282105 -0.0381206   0.05562177 -0.03530743 -0.01319344
   0.02424197 -0.00312998  0.05153564  0.00087946]
 [ 0.01094229 -0.0115445   0.01160178 -0.03359373 -0.01112978  0.07763909
  -0.03779947  0.02282105 -0.0381206   0.05562177 -0.03530743 -0.01319344
   0.02424197 -0.00312998  0.05153564  0.00087946]], shape=(2, 16), dtype=float32)
tf.Tensor(
[[ 0.01094229 -0.0115445   0.01160178 -0.03359373 -0.01112978  0.07763909
  -0.03779947  0.02282105 -0.0381

In [10]:
class BahdanauAttention(tf.keras.Model):
    def __init__(self, units):
        super(BahdanauAttention, self).__init__()
        self.W1 = tf.keras.layers.Dense(units)
        self.W2 = tf.keras.layers.Dense(units)
        self.V = tf.keras.layers.Dense(1)

    def call(self, query, values):
        # hidden shape == (batch_size, hidden size)
        # hidden_with_time_axis shape == (batch_size, 1, hidden size)
        # we are doing this to perform addition to calculate the score
        hidden_with_time_axis = tf.expand_dims(query, 1)

        # score shape == (batch_size, max_length, 1)
        # we get 1 at the last axis because we are applying score to self.V
        # the shape of the tensor before applying self.V is (batch_size, max_length, units)
        score = self.V(tf.nn.tanh(
            self.W1(values) + self.W2(hidden_with_time_axis)))
#         print("Score is :",score)
        # attention_weights shape == (batch_size, max_length, 1)
        attention_weights = tf.nn.softmax(score, axis=1)

        # context_vector shape after sum == (batch_size, hidden_size)
        context_vector = attention_weights * values
        context_vector = tf.reduce_sum(context_vector, axis=1)

        return context_vector, attention_weights

In [11]:
attention_layer = BahdanauAttention(10)
attention_result, attention_weights = attention_layer(state, output)
print(attention_result)
print(attention_weights)

tf.Tensor(
[[ 0.0260665   0.00831839  0.0087458   0.02841727  0.00547543  0.00237772
   0.0556828  -0.02215733  0.00440013  0.02172088  0.02116591 -0.01438401
  -0.00582038  0.01565367 -0.0174822   0.00196129]
 [ 0.0260665   0.00831839  0.0087458   0.02841727  0.00547543  0.00237772
   0.0556828  -0.02215733  0.00440013  0.02172088  0.02116591 -0.01438401
  -0.00582038  0.01565367 -0.0174822   0.00196129]], shape=(2, 16), dtype=float32)
tf.Tensor(
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]], shape=(2, 2, 1), dtype=float32)


In [12]:
class Decoder(tf.keras.Model):
    
    def __init__(self, units = 16,activation='tanh',recurrent_activation='sigmoid',return_state=True,return_sequence=False , vocab_size=30000 , embedding_dim=30 , batch_size=2):
        super(Decoder, self).__init__()
        self.units = units
        self.activation = activation
        self.recurrent_activation = recurrent_activation
        self.return_state = return_state
        self.return_sequence = return_sequence
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.batch_size = batch_size
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
#         self.gru = tf.keras.layers.GRU(self.dec_units,
#                                        return_sequences=True,
#                                        return_state=True,
#                                        recurrent_initializer='glorot_uniform')
        self.gru = tf.keras.layers.GRU(units=self.units , activation=self.activation , recurrent_activation=self.activation, return_sequences=self.return_sequence , return_state=self.return_state)

        self.fc = tf.keras.layers.Dense(vocab_size)

        # used for attention
        self.attention = BahdanauAttention(self.units)

    def call(self, x, hidden, output):
    # enc_output shape == (batch_size, max_length, hidden_size)
        context_vector, attention_weights = self.attention(hidden, output)

        # x shape after passing through embedding == (batch_size, 1, embedding_dim)
        x = self.embedding(x)

        # x shape after concatenation == (batch_size, 1, embedding_dim + hidden_size)
        x = tf.concat([tf.expand_dims(context_vector, 1), x], axis=-1)

        # passing the concatenated vector to the GRU
        output, state = self.gru(x)

        # output shape == (batch_size * 1, hidden_size)
        output = tf.reshape(output, (-1, output.shape[1]))

        # output shape == (batch_size, vocab)
        x = self.fc(output)

        return x, state, attention_weights


In [13]:
decoder = Decoder()

sample_decoder_output, _, _ = decoder(tf.random.uniform((2, 1)),
                                      output, state)

print ('Decoder output shape: (batch_size, vocab size) {}'.format(sample_decoder_output.shape))


Decoder output shape: (batch_size, vocab size) (2, 30000)


In [14]:
sample_decoder_output

<tf.Tensor: id=313399, shape=(2, 30000), dtype=float32, numpy=
array([[-1.5908470e-03, -5.2676239e-04, -7.7945594e-04, ...,
         3.1645558e-04, -1.8402003e-05,  4.2581014e-05],
       [-1.5908470e-03, -5.2676239e-04, -7.7945594e-04, ...,
         3.1645558e-04, -1.8402003e-05,  4.2581014e-05]], dtype=float32)>